* About
This is a set of standard potentials in C++ or Fortran. The goal is to provide
minimal, binding friendly interfaces for ease of usage from Python or even R.
The core library is header-only, though adapter functions are provided for
interfacing to ~Eigen~ and ~xtensor~.

This was originally designed for interfacing easily to potentials implemented [[http://theory.cm.utexas.edu/eon/][in
eOn]], but has grown to be more flexible.
** Usage
Setting up and running tests:
#+begin_src bash
pixi shell
meson setup bbdir -Dwith_tests=True --buildtype="debug"
meson test -C bbdir
#+end_src

~cmake~ works as well.
#+begin_src bash
cmake -B build -DPOTLIB_BUILD_TESTS=ON -DPOTLIB_BUILD_EXAMPLES=ON
cmake --build build
ctest --test-dir build
#+end_src

*** Developing locally
A ~pre-commit~ job is setup on CI to enforce consistent styles, so it is best to
set it up locally as well (using [[https://pypa.github.io/pipx][pipx]] for isolation):

#+begin_src sh
# Run before commiting
uvx pre-commit run --all-files
#+end_src
*** Handling actions
To keep the build matrix setup manageable, we use Nickel.
#+begin_src bash
pixi r gen-gha
#+end_src
* License
MIT, however note that some of the potentials are adapted from eOn which is
under a BSD 3-Clause License.
