#pragma once
// MIT License
// Copyright 2023--present rgpot developers

/**
 * @file rgpot.hpp
 * @author rgpot Developers
 * @date 2026-02-15
 * @brief Aggregate header for the rgpot C++ RAII API.
 *
 * Includes all public C++ headers in the correct dependency order.
 * Users may include just this file to access the full API surface:
 *
 * @code
 * #include "rgpot/rgpot.hpp"
 * @endcode
 *
 * @defgroup rgpot_cpp C++ RAII Wrappers
 * @brief Safe C++ wrappers around the Rust-core C ABI.
 *
 * The @c rgpot_cpp module provides move-only RAII handles and lightweight
 * view/owning types that map to the C structs generated by cbindgen.
 * Error handling is done via @c rgpot::Error exceptions, which are thrown
 * whenever the underlying C API returns a non-success status code.
 */

#include "rgpot/errors.hpp"
#include "rgpot/types.hpp"
#include "rgpot/potential.hpp"

#ifdef RGPOT_HAS_RPC
#include "rgpot/rpc_client.hpp"
#endif
