#pragma once
// MIT License
// Copyright 2023--present rgpot developers

/**
 * @file types.hpp
 * @author rgpot Developers
 * @date 2026-02-15
 * @brief C++ wrapper classes around the C API data exchange types.
 *
 * Provides two thin wrappers for the C structs generated by cbindgen:
 *
 * - @c InputSpec : a lightweight *view* over borrowed position, atom-type,
 *   and cell data.  Does not own the underlying memory.
 * - @c CalcResult : *owns* a force buffer and stores energy/variance scalars.
 *   Returned by @c PotentialHandle::calculate().
 *
 * These names are deliberately different from the legacy @c rgpot::ForceInput
 * and @c rgpot::ForceOut defined in @c ForceStructs.hpp to avoid name
 * collisions when both APIs are used in the same translation unit (e.g.,
 * inside the trampoline template in @c potential.hpp).
 *
 * @ingroup rgpot_cpp
 */

#include <cstddef>
#include <vector>

#include "rgpot.h"

namespace rgpot {

/**
 * @class InputSpec
 * @brief Lightweight view over input data for a potential calculation.
 * @ingroup rgpot_cpp
 *
 * Wraps @c rgpot_force_input_t.  All pointer fields are @b borrowed — the
 * caller must keep the underlying arrays alive for the lifetime of this
 * object.
 *
 * # Example
 * @code
 * double pos[] = {0,0,0, 1,0,0};
 * int    atm[] = {1, 1};
 * double box[] = {10,0,0, 0,10,0, 0,0,10};
 * rgpot::InputSpec input(2, pos, atm, box);
 * @endcode
 */
class InputSpec {
public:
  /**
   * @brief Construct from raw arrays (borrowed, not copied).
   * @param n_atoms Number of atoms in the configuration.
   * @param pos     Flat position array @c [n_atoms*3], row-major xyz.
   * @param atmnrs  Atomic number array @c [n_atoms].
   * @param box     Flat 3x3 cell matrix @c [9], row-major.
   */
  InputSpec(size_t n_atoms, const double *pos, const int *atmnrs,
            const double *box)
      : input_{n_atoms, pos, atmnrs, box} {}

  /**
   * @brief Construct from STL containers and a flat box pointer.
   * @param positions Flat position vector; size must be a multiple of 3.
   * @param atmnrs    Atomic number vector.
   * @param box       Flat 3x3 cell matrix @c [9], row-major.
   */
  InputSpec(const std::vector<double> &positions,
            const std::vector<int> &atmnrs, const double *box)
      : input_{positions.size() / 3, positions.data(), atmnrs.data(), box} {}

  /**
   * @brief Access the underlying C struct.
   * @return Const reference to the wrapped @c rgpot_force_input_t.
   */
  const rgpot_force_input_t &c_struct() const { return input_; }

  /**
   * @brief Returns the number of atoms.
   * @return Atom count.
   */
  size_t n_atoms() const { return input_.n_atoms; }

private:
  rgpot_force_input_t input_; //!< Wrapped C struct (borrowed pointers).
};

/**
 * @class CalcResult
 * @brief Owns the force buffer and stores energy/variance from a calculation.
 * @ingroup rgpot_cpp
 *
 * Wraps @c rgpot_force_out_t and manages the force array via
 * @c std::vector<double>.  The @c energy() and @c variance() accessors
 * read from the underlying C struct, which is filled by the Rust core during
 * @c rgpot_potential_calculate().
 */
class CalcResult {
public:
  /**
   * @brief Create a zeroed result buffer for @a n_atoms atoms.
   * @param n_atoms Number of atoms (forces buffer is @c n_atoms*3 doubles).
   */
  explicit CalcResult(size_t n_atoms)
      : forces_(n_atoms * 3, 0.0), output_{forces_.data(), 0.0, 0.0} {}

  /**
   * @brief Access the underlying C struct (mutable).
   * @return Mutable reference; used internally by @c PotentialHandle::calculate().
   */
  rgpot_force_out_t &c_struct() { return output_; }

  /**
   * @brief Returns the calculated potential energy.
   * @return Energy in the unit system of the potential.
   */
  double energy() const { return output_.energy; }

  /**
   * @brief Returns the variance / uncertainty estimate.
   * @return Variance (0.0 when not applicable).
   */
  double variance() const { return output_.variance; }

  /**
   * @brief Returns the force vector (const).
   * @return Const reference to the flat force array @c [n_atoms*3].
   */
  const std::vector<double> &forces() const { return forces_; }

  /**
   * @brief Returns the force vector (mutable).
   * @return Mutable reference for post-processing.
   */
  std::vector<double> &forces() { return forces_; }

private:
  std::vector<double> forces_; //!< Owned force buffer.
  rgpot_force_out_t output_;   //!< Wrapped C struct (points into @c forces_).
};

} // namespace rgpot
