concurrency:
  cancel-in-progress: true
  group: pages
jobs:
  build_docs:
    name: Build documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        activate-environment: true
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        environments: docs
        pixi-version: v0.62.1
    - name: Generate Docs
      run: pixi r docbld
      shell: pixi run bash -e {0}
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: documentation
        path: docs/build
    - if: github.event_name == 'push'
      name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        cname: rgpot.rgoswami.me
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
name: Build and Deploy Documentation
on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - '*'
  schedule:
  - cron: 0 8 * * 1
